server:
  port: 8082
feign:
  okhttp:
    enabled: true

#只定义一些共享配置中动态的部分
hm:
  db:
    database: hm-cart
  swagger:
    title: "黑马商城购物车服务接口文档"
    desc: "黑马商城购物车服务接口文档"
    package: com.hmall.cart.controller